# cypress path has to show to the directory which contains the package.json to run the cypresstest,
# it needs the script for "npm test"

apiVersion: cypresstest.testkube.io/v3
kind: Test
metadata:
  name: {{.Values.cypresstest.name}}-{{ .Release.Name }}
  namespace: testkube
  labels:
    saad: mygithubcypresstest
spec:
  content:
    repository:
      branch: {{((.Values.cypresstest).content).branch}}
      path:  {{((.Values.cypresstest).content).path}} #path to the test directory e.g. in cypress path to the package.json containing the script 'npm test'
      type: {{((.Values.cypresstest).content).type}}
      uri: {{((.Values.cypresstest).content).uri}} # url to git repository , doesn't need the suffix ".git" 
    type: {{((.Values.cypresstest).content).type}} # type is needed in repository and in content e.g. git-dir, git-file, string
  type: {{((.Values).cypresstest).type}} #test type e.g. cypress/project
