# parsing cypress und co as single file is not implemented yet!
# only works for curl , postman-collections
# currently without annotation kubectl.kubernetes.io/last-applied-configuration  it asks to repatch this missing part
    # example:     kubectl.kubernetes.io/last-applied-configuration : test.tests.testkube.io/postman-collection-as-gitfile

apiVersion: tests.testkube.io/v3
kind: Test
metadata:
  name: postman-collection-as-gitfile
  namespace: testkube
  annotations:
spec:
  content:
    repository:
      branch: main
      path: postman-collections/kubeshopexample.json
      type: git-file
      uri: https://github.com/saadisfy/testrepository
    type: git-file
  type: postman/collection