
{{ $releasename := .Release.Name }}
{{- range .Values.testsuites }}
--- # yaml document separator, so that helm knows while rendering that this will be multiple resources

apiVersion: tests.testkube.io/v2
kind: TestSuite
metadata:
  generation: 1
  name: {{ printf "%s%s" .name $releasename }} # because of that releasename must only consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character
  namespace: testkube
spec:
  description: someDescriptions
  schedule: {{.schedule | quote }}
  steps:
{{- range .steps }}
    {{ if .name }}
    - execute:
        name: {{ printf "%s-%s"  .name $releasename | quote }} #should be put in helper function so it remains same as the one in tests.yaml
    {{ else if .delayMilliseconds }}
    - delay:
        duration: {{ .delayMilliseconds }}
    {{else}}
    {{ end }}
{{ end }}
{{ end }}