tests:
  name: cypress # Test name prefix, {{ .Release.Name }} is appended. i.e. 
  content:
    uri: https://github.com/saadisfy/testrepository
    branch: main
    path: cypress/examples
    type: git-dir
  # Test type https://kubeshop.github.io/testkube/category/testtypes
  type: cypress/project
OtherMetaData:
  release:
    chart:
    name: test-config
    version: 0.0.1
  namespace: c000